dataset: stanford_cars
backbone: coatnet_2_rw_224.sw_in12k_ft_in1k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 5
lr1: 5.928208284817785e-05
lr2: 0.030297113417160997
weight_decay1: 9.246056949885325e-06
weight_decay2: 1.2460526070886074e-06
scheduler: true
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_paper_final5
exp_id: coatnet_2_rw_224.sw_in12k_ft_in1k_stanford_cars_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
