dataset: oxford-iiit-pet
backbone: coatnet_2_rw_224.sw_in12k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 5
lr1: 0.010667351953314313
lr2: 0.0005503199372331198
weight_decay1: 9.774762650558306e-06
weight_decay2: 1.1043002244559489e-06
scheduler: true
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_paper_final5
exp_id: coatnet_2_rw_224.sw_in12k_oxford-iiit-pet_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
