dataset: stanford_cars
backbone: convnext_tiny.fb_in22k_ft_in1k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 5
lr1: 0.0001583155296638244
lr2: 0.045924322392542495
weight_decay1: 0.0018164657647576023
weight_decay2: 2.9446118109973152e-05
scheduler: false
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_paper_final5
exp_id: convnext_tiny.fb_in22k_ft_in1k_stanford_cars_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
