dataset: stanford_cars
backbone: eva02_tiny_patch14_224.mim_in22k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 5
lr1: 1.8998791166222962e-05
lr2: 0.010314486176700598
weight_decay1: 8.155451657516297e-05
weight_decay2: 3.4463107491721995e-06
scheduler: true
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_paper_final5
exp_id: eva02_tiny_patch14_224.mim_in22k_stanford_cars_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
