dataset: stanford_cars
backbone: eva02_base_patch14_224.mim_in22k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 5
lr1: 0.0001477123750130932
lr2: 8.17216800486828e-05
weight_decay1: 7.57105080236878e-05
weight_decay2: 0.00827815238590798
scheduler: true
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_paper_final5
exp_id: eva02_base_patch14_224.mim_in22k_stanford_cars_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
