dataset: oxford-iiit-pet
backbone: swin_tiny_patch4_window7_224.ms_in1k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 5
lr1: 0.0005165139546699323
lr2: 0.02631970770540126
weight_decay1: 1.259552297035583e-05
weight_decay2: 2.705639562704845e-06
scheduler: true
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_paper_final5
exp_id: swin_tiny_patch4_window7_224.ms_in1k_oxford-iiit-pet_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
