dataset: oxford-iiit-pet
backbone: vit_base_patch16_224.augreg_in21k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 5
lr1: 1.1830860514759755e-05
lr2: 9.980958823253834e-05
weight_decay1: 3.266993247351843e-05
weight_decay2: 4.90980088471928e-06
scheduler: true
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_paper_final5
exp_id: vit_base_patch16_224.augreg_in21k_oxford-iiit-pet_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
