dataset: stanford_cars
backbone: vit_small_patch16_224.augreg_in1k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 5
lr1: 2.4514614300077984e-06
lr2: 0.0004113335982438347
weight_decay1: 0.009339527722542092
weight_decay2: 0.0017938927020219868
scheduler: false
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_paper_final5
exp_id: vit_small_patch16_224.augreg_in1k_stanford_cars_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
