dataset: fgvc-aircraft-2013b
backbone: convnext_tiny.fb_in22k_ft_in1k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 50
lr1: 1.4820285018742478e-06
lr2: 0.0013187119216379328
weight_decay1: 0.000439079257324
weight_decay2: 1.5630799020950923e-05
scheduler: true
nb_completed_trials: 208
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_paper_final3
exp_id: convnext_tiny.fb_in22k_ft_in1k_fgvc-aircraft-2013b_TRADES_v2
statedicts_path: /home/rishika/scratch/robust_training_data/state_dicts
trained_statedicts_path: /home/rishika/scratch/robust_training_data/trained_state_dicts/
datasets_path: /home/rishika/scratch/robust_training_data/compressed_datasets
hpo_path: /home/rishika/scratch/robust_training_data/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
