dataset: uc-merced-land-use-dataset
backbone: vit_base_patch16_224.mae
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 50
lr1: 4.0431260261004145e-06
lr2: 1.6701650552273647e-06
weight_decay1: 2.6913892686855095e-06
weight_decay2: 7.995347689531275e-06
scheduler: true
nb_completed_trials: 227
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_paper_final3
exp_id: vit_base_patch16_224.mae_uc-merced-land-use-dataset_CLASSIC_AT
statedicts_path: /home/rishika/scratch/robust_training_data/state_dicts
trained_statedicts_path: /home/rishika/scratch/robust_training_data/trained_state_dicts/
datasets_path: /home/rishika/scratch/robust_training_data/compressed_datasets
hpo_path: /home/rishika/scratch/robust_training_data/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
