dataset: flowers-102
backbone: vit_small_patch16_224.dino
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 50
lr1: 1.3522435991628919e-06
lr2: 1.3852636558523316e-06
weight_decay1: 9.657045339595033e-06
weight_decay2: 0.0027549377795644306
scheduler: false
nb_completed_trials: 273
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_paper_final3
exp_id: vit_small_patch16_224.dino_flowers-102_TRADES_v2
statedicts_path: /home/rishika/scratch/robust_training_data/state_dicts
trained_statedicts_path: /home/rishika/scratch/robust_training_data/trained_state_dicts/
datasets_path: /home/rishika/scratch/robust_training_data/compressed_datasets
hpo_path: /home/rishika/scratch/robust_training_data/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
