dataset: flowers-102
backbone: vit_base_patch16_clip_224.laion2b_ft_in1k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 50
lr1: 5.928208284817785e-05
lr2: 0.030297113417160997
weight_decay1: 9.246056949885325e-06
weight_decay2: 1.2460526070886074e-06
scheduler: true
nb_completed_trials: 242
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_paper_final3
exp_id: vit_base_patch16_clip_224.laion2b_ft_in1k_flowers-102_TRADES_v2
statedicts_path: /home/rishika/scratch/robust_training_data/state_dicts
trained_statedicts_path: /home/rishika/scratch/robust_training_data/trained_state_dicts/
datasets_path: /home/rishika/scratch/robust_training_data/compressed_datasets
hpo_path: /home/rishika/scratch/robust_training_data/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
