dataset: oxford-iiit-pet
backbone: vit_small_patch16_224.augreg_in1k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 50
lr1: 0.021008601838997464
lr2: 4.1058680104523756e-05
weight_decay1: 0.00048212001694162833
weight_decay2: 6.36056573999679e-05
scheduler: true
nb_completed_trials: 252
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_paper_final3
exp_id: vit_small_patch16_224.augreg_in1k_oxford-iiit-pet_CLASSIC_AT
statedicts_path: /home/rishika/scratch/robust_training_data/state_dicts
trained_statedicts_path: /home/rishika/scratch/robust_training_data/trained_state_dicts/
datasets_path: /home/rishika/scratch/robust_training_data/compressed_datasets
hpo_path: /home/rishika/scratch/robust_training_data/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
