dataset: stanford_cars
backbone: CLIP-convnext_base_w-laion2B-s13B-b82K
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 5
lr1: 3.1765804142268105e-05
lr2: 0.001330885467621426
weight_decay1: 0.0003883962400562118
weight_decay2: 1.9377623573934265e-06
scheduler: false
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_paper_final4
exp_id: CLIP-convnext_base_w-laion2B-s13B-b82K_stanford_cars_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
