dataset: flowers-102
backbone: convnext_tiny.fb_in22k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 0
epochs: 1
lr1: 0.000554711947159213
lr2: 0.003766576841599297
weight_decay1: 0.00025766385746135907
weight_decay2: 0.00015119336467641012
scheduler: false
nb_completed_trials: 1
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_reproduce
exp_id: convnext_tiny.fb_in22k_flowers-102_TRADES_v2
statedicts_path: ~/my_backbones/
trained_statedicts_path: ~/my_backbones/trained_state_dicts/
datasets_path: ~/data/
hpo_path: ~/hpo_results/
work_path: ~/work_dir/
configs_path: ./configs/
results_path: ./results/
