dataset: oxford-iiit-pet
backbone: coatnet_0_rw_224.sw_in1k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 5
lr1: 7.759999215461018e-06
lr2: 0.010376263015793929
weight_decay1: 1.0368965357499977e-05
weight_decay2: 1.4562120488585128e-05
scheduler: false
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_paper_final1
exp_id: coatnet_0_rw_224.sw_in1k_oxford-iiit-pet_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
