dataset: stanford_cars
backbone: convnext_base.clip_laion2b_augreg_ft_in12k_in1k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 5
lr1: 1.9454247868299837e-05
lr2: 0.0006622831701518804
weight_decay1: 3.3862462111748364e-06
weight_decay2: 3.078581942280645e-05
scheduler: true
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_paper_final1
exp_id: convnext_base.clip_laion2b_augreg_ft_in12k_in1k_stanford_cars_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
