dataset: stanford_cars
backbone: swin_base_patch4_window7_224.ms_in22k_ft_in1k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 5
lr1: 8.036752987046991e-05
lr2: 0.005614247491665514
weight_decay1: 0.00011080667247036247
weight_decay2: 0.0001458166846972585
scheduler: false
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_paper_final1
exp_id: swin_base_patch4_window7_224.ms_in22k_ft_in1k_stanford_cars_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
