dataset: uc-merced-land-use-dataset
backbone: edgenext_small.usi_in1k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 5
lr1: 0.005067313558534072
lr2: 3.114592335403677e-05
weight_decay1: 6.567990431991947e-06
weight_decay2: 0.008453305504109028
scheduler: false
nb_completed_trials: 286
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: ‘full_fine_tuning_5epochs_edge_article1’
exp_id: edgenext_small.usi_in1k_uc-merced-land-use-dataset_TRADES_v2
statedicts_path: /home/rishika/scratch/robust_training_data/state_dicts
trained_statedicts_path: /home/rishika/scratch/robust_training_data/trained_state_dicts/
datasets_path: /home/rishika/scratch/robust_training_data/compressed_datasets
hpo_path: /home/rishika/scratch/robust_training_data/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
