dataset: oxford-iiit-pet
backbone: efficientnet-b0
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 5
lr1: 3.690803219673014e-05
lr2: 0.0028947634357865313
weight_decay1: 0.0032029975700290426
weight_decay2: 0.00378814552109712
scheduler: true
nb_completed_trials: 244
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: ‘full_fine_tuning_5epochs_edge_article1’
exp_id: efficientnet-b0_oxford-iiit-pet_CLASSIC_AT
statedicts_path: /home/rishika/scratch/robust_training_data/state_dicts
trained_statedicts_path: /home/rishika/scratch/robust_training_data/trained_state_dicts/
datasets_path: /home/rishika/scratch/robust_training_data/compressed_datasets
hpo_path: /home/rishika/scratch/robust_training_data/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
