dataset: oxford-iiit-pet
backbone: mobilenetv3_large_100.ra_in1k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 5
lr1: 0.0015750864825927514
lr2: 0.0004200989012085034
weight_decay1: 0.005003015882580475
weight_decay2: 1.130282704078043e-05
scheduler: false
nb_completed_trials: 251
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: ‘full_fine_tuning_5epochs_edge_article1’
exp_id: mobilenetv3_large_100.ra_in1k_oxford-iiit-pet_TRADES_v2
statedicts_path: /home/rishika/scratch/robust_training_data/state_dicts
trained_statedicts_path: /home/rishika/scratch/robust_training_data/trained_state_dicts/
datasets_path: /home/rishika/scratch/robust_training_data/compressed_datasets
hpo_path: /home/rishika/scratch/robust_training_data/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
