dataset: fgvc-aircraft-2013b
backbone: regnetx_004.pycls_in1k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 5
lr1: 9.613989345165609e-05
lr2: 8.700690210600536e-05
weight_decay1: 0.00047751184301655973
weight_decay2: 0.0055227614309091245
scheduler: true
nb_completed_trials: 221
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: ‘full_fine_tuning_5epochs_edge_article1’
exp_id: regnetx_004.pycls_in1k_fgvc-aircraft-2013b_TRADES_v2
statedicts_path: /home/rishika/scratch/robust_training_data/state_dicts
trained_statedicts_path: /home/rishika/scratch/robust_training_data/trained_state_dicts/
datasets_path: /home/rishika/scratch/robust_training_data/compressed_datasets
hpo_path: /home/rishika/scratch/robust_training_data/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
