dataset: stanford_cars
backbone: vit_base_patch16_224.augreg_in21k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 5
lr1: 1.2378696725754973e-05
lr2: 0.001338666595669606
weight_decay1: 3.3172551970349164e-06
weight_decay2: 0.00017613100927540168
scheduler: true
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_paper
exp_id: vit_base_patch16_224.augreg_in21k_stanford_cars_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
