dataset: stanford_cars
backbone: vit_base_patch16_224.augreg_in21k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 5
lr1: 0.002978888635819277
lr2: 1.1001630263565295e-05
weight_decay1: 0.0001427279835988909
weight_decay2: 1.0281863322848681e-06
scheduler: false
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_paper
exp_id: vit_base_patch16_224.augreg_in21k_stanford_cars_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
