dataset: stanford_cars
backbone: swin_base_patch4_window7_224.ms_in22k_ft_in1k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 5
lr1: 0.0007749721157015397
lr2: 8.31861467974369e-06
weight_decay1: 0.0014181329089465852
weight_decay2: 0.00028062393372483446
scheduler: false
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_paper_final3
exp_id: swin_base_patch4_window7_224.ms_in22k_ft_in1k_stanford_cars_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
