dataset: fgvc-aircraft-2013b
backbone: eva02_base_patch14_224.mim_in22k
ft_type: linear_probing
loss_function: CLASSIC_AT
seed: 1
epochs: 50
lr1: 0.001
lr2: 0.00012164941464151844
weight_decay1: 0.0
weight_decay2: 0.0007608481233714791
scheduler: false
nb_completed_trials: 3
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: linearprobe_50epochs_budget
exp_id: eva02_base_patch14_224.mim_in22k_fgvc-aircraft-2013b_CLASSIC_AT
statedicts_path: /home/rishika/scratch/robust_training_data/state_dicts
trained_statedicts_path: /home/rishika/scratch/robust_training_data/trained_state_dicts/
datasets_path: /home/rishika/scratch/robust_training_data/compressed_datasets
hpo_path: /home/rishika/scratch/robust_training_data/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
