dataset: uc-merced-land-use-dataset
backbone: resnet50.a1_in1k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 50
lr1: 0.00378333489840534
lr2: 0.003925148968098255
weight_decay1: 0.0007943179566007689
weight_decay2: 0.0038193005765592663
scheduler: false
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_final3
exp_id: resnet50.a1_in1k_uc-merced-land-use-dataset_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
