dataset: caltech101
backbone: robust_deit_small_patch16_224
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 50
lr1: 4.044822649197344e-05
lr2: 0.003601698830774201
weight_decay1: 0.00018308318127610826
weight_decay2: 7.493131437373717e-05
scheduler: true
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_final3
exp_id: robust_deit_small_patch16_224_caltech101_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
