dataset: stanford_cars
backbone: deit_small_patch16_224.fb_in1k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 5
lr1: 0.07424576981970668
lr2: 0.00012980019737052719
weight_decay1: 8.59983448909145e-06
weight_decay2: 2.3239445781642355e-06
scheduler: true
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_final100
exp_id: deit_small_patch16_224.fb_in1k_stanford_cars_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
