dataset: stanford_cars
backbone: robust_deit_small_patch16_224
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 5
lr1: 0.00014401607971568404
lr2: 0.012450796902850916
weight_decay1: 5.139836656089975e-05
weight_decay2: 0.0017013498864865112
scheduler: false
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_final100
exp_id: robust_deit_small_patch16_224_stanford_cars_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
