dataset: caltech101
backbone: vit_base_patch16_224.augreg_in1k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 5
lr1: 0.00021306748753283612
lr2: 0.0034194817832802365
weight_decay1: 0.0004939209853980815
weight_decay2: 0.0003256904134297838
scheduler: false
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_final100
exp_id: vit_base_patch16_224.augreg_in1k_caltech101_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
