dataset: uc-merced-land-use-dataset
backbone: coatnet_2_rw_224.sw_in12k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 5
lr1: 0.0004647746719721332
lr2: 0.05619409646508126
weight_decay1: 9.380767542427003e-05
weight_decay2: 0.00014534564894374584
scheduler: false
nb_completed_trials: 222
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_article1
exp_id: coatnet_2_rw_224.sw_in12k_uc-merced-land-use-dataset_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
