dataset: flowers-102
backbone: coatnet_0_rw_224.sw_in1k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 5
lr1: 0.002084362379893362
lr2: 0.00037535789963654304
weight_decay1: 0.006003147633638409
weight_decay2: 0.00022193212012672315
scheduler: false
nb_completed_trials: 294
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_article1
exp_id: coatnet_0_rw_224.sw_in1k_flowers-102_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
