dataset: uc-merced-land-use-dataset
backbone: coatnet_0_rw_224.sw_in1k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 5
lr1: 0.00041084986459893116
lr2: 0.004831225725349887
weight_decay1: 4.5880110941328475e-06
weight_decay2: 0.0005600582122085054
scheduler: true
nb_completed_trials: 305
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_article1
exp_id: coatnet_0_rw_224.sw_in1k_uc-merced-land-use-dataset_CLASSIC_AT
statedicts_path: /home/rishika/scratch/robust_training_data/state_dicts
trained_statedicts_path: /home/rishika/scratch/robust_training_data/trained_state_dicts/
datasets_path: /home/rishika/scratch/robust_training_data/compressed_datasets
hpo_path: /home/rishika/scratch/robust_training_data/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
