dataset: flowers-102
backbone: convnext_tiny.fb_in1k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 5
lr1: 0.0003939232470227544
lr2: 0.011218726313351357
weight_decay1: 1.1230913132227974e-06
weight_decay2: 0.0004896428065968716
scheduler: true
nb_completed_trials: 318
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_article1
exp_id: convnext_tiny.fb_in1k_flowers-102_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
