dataset: uc-merced-land-use-dataset
backbone: deit_small_patch16_224.fb_in1k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 5
lr1: 1.2312741855776608e-06
lr2: 0.002809116335314592
weight_decay1: 0.0030500790620178247
weight_decay2: 2.6426101893463228e-05
scheduler: false
nb_completed_trials: 341
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_article1
exp_id: deit_small_patch16_224.fb_in1k_uc-merced-land-use-dataset_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
