dataset: fgvc-aircraft-2013b
backbone: eva02_tiny_patch14_224.mim_in22k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 5
lr1: 0.0026674574591455755
lr2: 1.0525948689799705e-05
weight_decay1: 0.0032543911150884836
weight_decay2: 1.2869165107815028e-06
scheduler: true
nb_completed_trials: 238
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_article1
exp_id: eva02_tiny_patch14_224.mim_in22k_fgvc-aircraft-2013b_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
