dataset: flowers-102
backbone: eva02_tiny_patch14_224.mim_in22k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 5
lr1: 3.561551174992038e-05
lr2: 9.219371911578081e-05
weight_decay1: 2.10443213206796e-06
weight_decay2: 2.561446266878037e-05
scheduler: true
nb_completed_trials: 309
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_article1
exp_id: eva02_tiny_patch14_224.mim_in22k_flowers-102_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
