dataset: uc-merced-land-use-dataset
backbone: resnet50.a1_in1k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 5
lr1: 5.244622350744561e-06
lr2: 3.380579956287871e-05
weight_decay1: 0.0035292454533101245
weight_decay2: 0.0035266934290050767
scheduler: false
nb_completed_trials: 354
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_article1
exp_id: resnet50.a1_in1k_uc-merced-land-use-dataset_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
