dataset: uc-merced-land-use-dataset
backbone: robust_vit_base_patch16_224
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 5
lr1: 0.021008601838997464
lr2: 4.1058680104523756e-05
weight_decay1: 0.00048212001694162833
weight_decay2: 6.36056573999679e-05
scheduler: true
nb_completed_trials: 270
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_article1
exp_id: robust_vit_base_patch16_224_uc-merced-land-use-dataset_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
