dataset: fgvc-aircraft-2013b
backbone: vit_base_patch16_224.mae
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 5
lr1: 7.2728150208881555e-06
lr2: 4.849296602698792e-06
weight_decay1: 0.005375041876450287
weight_decay2: 0.0006127349401923009
scheduler: false
nb_completed_trials: 224
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_article1
exp_id: vit_base_patch16_224.mae_fgvc-aircraft-2013b_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
