dataset: uc-merced-land-use-dataset
backbone: vit_base_patch16_224.augreg_in1k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 5
lr1: 5.2811402442263535e-06
lr2: 0.0057232021463439675
weight_decay1: 7.730303750616765e-06
weight_decay2: 0.0001195108396012332
scheduler: false
nb_completed_trials: 274
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_article1
exp_id: vit_base_patch16_224.augreg_in1k_uc-merced-land-use-dataset_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
