dataset: fgvc-aircraft-2013b
backbone: vit_small_patch16_224.augreg_in21k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 5
lr1: 5.4806150470064783e-05
lr2: 0.0056762369400532595
weight_decay1: 0.000801663187901747
weight_decay2: 0.003413692239351968
scheduler: false
nb_completed_trials: 249
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_article1
exp_id: vit_small_patch16_224.augreg_in21k_fgvc-aircraft-2013b_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
