dataset: caltech101
backbone: vit_small_patch16_224.augreg_in21k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 5
lr1: 0.0015750864825927514
lr2: 0.0004200989012085034
weight_decay1: 0.005003015882580475
weight_decay2: 1.130282704078043e-05
scheduler: false
nb_completed_trials: 256
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_article1
exp_id: vit_small_patch16_224.augreg_in21k_caltech101_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
