dataset: oxford-iiit-pet
backbone: vit_small_patch16_224.augreg_in21k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 5
lr1: 1.249090035686812e-06
lr2: 2.163516693024963e-06
weight_decay1: 0.001766387807497407
weight_decay2: 0.0003508830920026724
scheduler: false
nb_completed_trials: 280
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_article1
exp_id: vit_small_patch16_224.augreg_in21k_oxford-iiit-pet_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
