dataset: stanford_cars
backbone: vit_small_patch16_224.dino
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 5
lr1: 1.848471358009254e-06
lr2: 0.0007423146427788864
weight_decay1: 3.862907418494318e-06
weight_decay2: 0.00022762614721505583
scheduler: true
nb_completed_trials: 242
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_article1
exp_id: vit_small_patch16_224.dino_stanford_cars_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
