dataset: fgvc-aircraft-2013b
backbone: vit_small_patch16_224.dino
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 5
lr1: 0.05809725572644378
lr2: 1.2358511353661582e-05
weight_decay1: 9.8809977477913e-06
weight_decay2: 0.0028523786588596314
scheduler: false
nb_completed_trials: 248
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_article1
exp_id: vit_small_patch16_224.dino_fgvc-aircraft-2013b_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
