dataset: flowers-102
backbone: deit_small_patch16_224.fb_in1k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 50
lr1: 0.00625547088532716
lr2: 0.00010752799030917345
weight_decay1: 0.0006566593112225631
weight_decay2: 0.00021950117839400309
scheduler: true
nb_completed_trials: 287
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_rebuttal2
exp_id: deit_small_patch16_224.fb_in1k_flowers-102_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
