dataset: fgvc-aircraft-2013b
backbone: resnet50.a1_in1k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 50
lr1: 0.0004632617302122406
lr2: 0.0028799541239828896
weight_decay1: 1.8283634209844514e-05
weight_decay2: 0.0005571905096939264
scheduler: true
nb_completed_trials: 207
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_rebuttal2
exp_id: resnet50.a1_in1k_fgvc-aircraft-2013b_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
