dataset: flowers-102
backbone: robust_convnext_tiny
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 50
lr1: 0.0006384855843742663
lr2: 1.2394712193688833e-06
weight_decay1: 0.0015941555325149704
weight_decay2: 8.548641316667401e-06
scheduler: false
nb_completed_trials: 241
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_rebuttal2
exp_id: robust_convnext_tiny_flowers-102_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
