dataset: flowers-102
backbone: robust_deit_small_patch16_224
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 50
lr1: 1.2384572243648865e-06
lr2: 2.239291948629666e-06
weight_decay1: 8.818210135856339e-05
weight_decay2: 0.0002662673074410208
scheduler: false
nb_completed_trials: 232
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_rebuttal2
exp_id: robust_deit_small_patch16_224_flowers-102_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
