dataset: flowers-102
backbone: robust_vit_base_patch16_224
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 50
lr1: 0.0004561758150522565
lr2: 3.521116041991218e-06
weight_decay1: 3.838229897022728e-06
weight_decay2: 0.00010843137252669625
scheduler: true
nb_completed_trials: 232
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_rebuttal2
exp_id: robust_vit_base_patch16_224_flowers-102_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
