dataset: stanford_cars
backbone: robust_convnext_tiny
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 50
lr1: 1.4820285018742478e-06
lr2: 0.0013187119216379328
weight_decay1: 0.000439079257324
weight_decay2: 1.5630799020950923e-05
scheduler: true
nb_completed_trials: 208
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_rebuttal2
exp_id: robust_convnext_tiny_stanford_cars_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
