dataset: oxford-iiit-pet
backbone: vit_small_patch16_224.augreg_in21k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 50
lr1: 0.0001737404360263286
lr2: 0.0288854647855878
weight_decay1: 3.238451256068134e-05
weight_decay2: 0.00014246191473875792
scheduler: false
nb_completed_trials: 244
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_rebuttal2
exp_id: vit_small_patch16_224.augreg_in21k_oxford-iiit-pet_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
