dataset: stanford_cars
backbone: vit_small_patch16_224.augreg_in1k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 50
lr1: 9.613989345165609e-05
lr2: 8.700690210600536e-05
weight_decay1: 0.00047751184301655973
weight_decay2: 0.0055227614309091245
scheduler: true
nb_completed_trials: 208
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_rebuttal2
exp_id: vit_small_patch16_224.augreg_in1k_stanford_cars_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
