dataset: oxford-iiit-pet
backbone: vit_base_patch16_clip_224.laion2b_ft_in1k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 50
lr1: 0.00019320752621429857
lr2: 0.00014239437572248639
weight_decay1: 0.005708357416333576
weight_decay2: 0.001298843859025954
scheduler: false
nb_completed_trials: 204
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_rebuttal2
exp_id: vit_base_patch16_clip_224.laion2b_ft_in1k_oxford-iiit-pet_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
