dataset: uc-merced-land-use-dataset
backbone: convnext_tiny.fb_in1k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 0
epochs: 5
lr1: 0.001567667719550604
lr2: 0.0072570057215942665
weight_decay1: 0.0002576638574613588
weight_decay2: 0.00015119336467640996
scheduler: false
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_final1
exp_id: convnext_tiny.fb_in1k_uc-merced-land-use-dataset_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
