dataset: stanford_cars
backbone: CLIP-convnext_base_w-laion_aesthetic-s13B-b82K
ft_type: linear_probing
loss_function: CLASSIC_AT
seed: 1
epochs: 50
lr1: 0.001
lr2: 0.00012164941464151844
weight_decay1: 0.0
weight_decay2: 0.0007608481233714791
scheduler: false
nb_completed_trials: 201
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: linearprobe_50epochs_paper_final2
exp_id: CLIP-convnext_base_w-laion_aesthetic-s13B-b82K_stanford_cars_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
