dataset: flowers-102
backbone: robust_convnext_tiny
ft_type: linear_probing
loss_function: CLASSIC_AT
seed: 1
epochs: 50
lr1: 0.001
lr2: 4.4683055229351265e-06
weight_decay1: 0.0
weight_decay2: 1.1952749874776883e-06
scheduler: false
nb_completed_trials: 230
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: linearprobe_50epochs_paper_final2
exp_id: robust_convnext_tiny_flowers-102_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
