dataset: flowers-102
backbone: robust_vit_base_patch16_224
ft_type: linear_probing
loss_function: TRADES_v2
seed: 1
epochs: 50
lr1: 0.001
lr2: 5.343227125594116e-05
weight_decay1: 0.0
weight_decay2: 3.8642916535526504e-05
scheduler: true
nb_completed_trials: 211
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: linearprobe_50epochs_paper_final2
exp_id: robust_vit_base_patch16_224_flowers-102_TRADES_v2
statedicts_path: ~/scratch/state_dicts/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
