dataset: flowers-102
backbone: vit_base_patch16_224.augreg_in21k_ft_in1k
ft_type: linear_probing
loss_function: TRADES_v2
seed: 1
epochs: 50
lr1: 0.001
lr2: 0.0022817627560812207
weight_decay1: 0.0
weight_decay2: 4.437634363159821e-05
scheduler: false
nb_completed_trials: 218
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: linearprobe_50epochs_paper_final2
exp_id: vit_base_patch16_224.augreg_in21k_ft_in1k_flowers-102_TRADES_v2
statedicts_path: ~/scratch/state_dicts/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
