dataset: uc-merced-land-use-dataset
backbone: vit_base_patch16_224.mae
ft_type: linear_probing
loss_function: CLASSIC_AT
seed: 1
epochs: 50
lr1: 0.001
lr2: 3.7807516906122444e-05
weight_decay1: 0.0
weight_decay2: 0.0005571905096939264
scheduler: true
nb_completed_trials: 212
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: linearprobe_50epochs_paper_final2
exp_id: vit_base_patch16_224.mae_uc-merced-land-use-dataset_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: ~/scratch/data/
hpo_path: ~/scratch/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
