dataset: uc-merced-land-use-dataset
backbone: CLIP-convnext_base_w-laion_aesthetic-s13B-b82K
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 50
lr1: 0.00011186451269342267
lr2: 0.010015892466752692
weight_decay1: 6.728237446164208e-05
weight_decay2: 1.6893426773335825e-06
scheduler: true
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_final2
exp_id: CLIP-convnext_base_w-laion_aesthetic-s13B-b82K_uc-merced-land-use-dataset_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
