dataset: uc-merced-land-use-dataset
backbone: resnet50.a1_in1k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 50
lr1: 0.004711464845678526
lr2: 0.005314213759893315
weight_decay1: 0.0029414210765082503
weight_decay2: 3.384745147186885e-06
scheduler: false
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_final2
exp_id: resnet50.a1_in1k_uc-merced-land-use-dataset_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
