dataset: uc-merced-land-use-dataset
backbone: robust_resnet50
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 50
lr1: 0.00017544159878153505
lr2: 0.000890794652126256
weight_decay1: 0.003027085336875635
weight_decay2: 1.4509509140020804e-05
scheduler: true
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_final2
exp_id: robust_resnet50_uc-merced-land-use-dataset_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
