dataset: flowers-102
backbone: edgenext_small.usi_in1k
ft_type: linear_probing
loss_function: CLASSIC_AT
seed: 1
epochs: 50
lr1: 0.001
lr2: 3.6844068804921994e-05
weight_decay1: 0.0
weight_decay2: 0.000125369714912942
scheduler: true
nb_completed_trials: 205
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: ‘linearprobe_50epochs_edge_paper_final2’
exp_id: edgenext_small.usi_in1k_flowers-102_CLASSIC_AT
statedicts_path: /home/rishika/scratch/robust_training_data/state_dicts
trained_statedicts_path: /home/rishika/scratch/robust_training_data/trained_state_dicts/
datasets_path: /home/rishika/scratch/robust_training_data/compressed_datasets
hpo_path: /home/rishika/scratch/robust_training_data/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
