dataset: uc-merced-land-use-dataset
backbone: swin_tiny_patch4_window7_224.ms_in1k
ft_type: linear_probing
loss_function: TRADES_v2
seed: 0
epochs: 50
lr1: 0.001
lr2: 0.001567667719550604
weight_decay1: 0.0
weight_decay2: 0.0007257005721594274
scheduler: false
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: linearprobe_50epochs_final1
exp_id: swin_tiny_patch4_window7_224.ms_in1k_uc-merced-land-use-dataset_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
