dataset: uc-merced-land-use-dataset
backbone: convnext_tiny.fb_in22k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 50
lr1: 0.0004350841191394324
lr2: 0.010251924992138665
weight_decay1: 0.00019496383939788994
weight_decay2: 0.0008561899014864636
scheduler: true
nb_completed_trials: 253
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_paper_final2
exp_id: convnext_tiny.fb_in22k_uc-merced-land-use-dataset_CLASSIC_AT
statedicts_path: /home/rishika/scratch/robust_training_data/state_dicts
trained_statedicts_path: /home/rishika/scratch/robust_training_data/trained_state_dicts/
datasets_path: /home/rishika/scratch/robust_training_data/compressed_datasets
hpo_path: /home/rishika/scratch/robust_training_data/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
