dataset: flowers-102
backbone: convnext_tiny.fb_in22k_ft_in1k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 50
lr1: 7.2728150208881555e-06
lr2: 4.849296602698792e-06
weight_decay1: 0.005375041876450287
weight_decay2: 0.0006127349401923009
scheduler: false
nb_completed_trials: 246
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_paper_final2
exp_id: convnext_tiny.fb_in22k_ft_in1k_flowers-102_CLASSIC_AT
statedicts_path: /home/rishika/scratch/robust_training_data/state_dicts
trained_statedicts_path: /home/rishika/scratch/robust_training_data/trained_state_dicts/
datasets_path: /home/rishika/scratch/robust_training_data/compressed_datasets
hpo_path: /home/rishika/scratch/robust_training_data/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
