dataset: flowers-102
backbone: deit_small_patch16_224.fb_in1k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 50
lr1: 2.999827229672451e-06
lr2: 6.471836718439119e-06
weight_decay1: 2.6659667002898226e-05
weight_decay2: 2.405643357505913e-06
scheduler: false
nb_completed_trials: 262
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_paper_final2
exp_id: deit_small_patch16_224.fb_in1k_flowers-102_TRADES_v2
statedicts_path: /home/rishika/scratch/robust_training_data/state_dicts
trained_statedicts_path: /home/rishika/scratch/robust_training_data/trained_state_dicts/
datasets_path: /home/rishika/scratch/robust_training_data/compressed_datasets
hpo_path: /home/rishika/scratch/robust_training_data/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
