dataset: oxford-iiit-pet
backbone: deit_small_patch16_224.fb_in1k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 50
lr1: 0.05118995452802043
lr2: 7.92531319554213e-05
weight_decay1: 0.001126367974242319
weight_decay2: 0.001220056638076919
scheduler: true
nb_completed_trials: 233
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_paper_final2
exp_id: deit_small_patch16_224.fb_in1k_oxford-iiit-pet_TRADES_v2
statedicts_path: /home/rishika/scratch/robust_training_data/state_dicts
trained_statedicts_path: /home/rishika/scratch/robust_training_data/trained_state_dicts/
datasets_path: /home/rishika/scratch/robust_training_data/compressed_datasets
hpo_path: /home/rishika/scratch/robust_training_data/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
