dataset: flowers-102
backbone: eva02_tiny_patch14_224.mim_in22k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 50
lr1: 0.006652162523224
lr2: 0.00021725181617391476
weight_decay1: 1.1912535422153591e-05
weight_decay2: 0.0021221220406342895
scheduler: false
nb_completed_trials: 225
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_paper_final2
exp_id: eva02_tiny_patch14_224.mim_in22k_flowers-102_TRADES_v2
statedicts_path: /home/rishika/scratch/robust_training_data/state_dicts
trained_statedicts_path: /home/rishika/scratch/robust_training_data/trained_state_dicts/
datasets_path: /home/rishika/scratch/robust_training_data/compressed_datasets
hpo_path: /home/rishika/scratch/robust_training_data/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
