dataset: fgvc-aircraft-2013b
backbone: robust_deit_small_patch16_224
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 50
lr1: 0.0003477264188160535
lr2: 1.1036758972640384e-05
weight_decay1: 1.57476944267626e-06
weight_decay2: 0.00011897275088709404
scheduler: false
nb_completed_trials: 222
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_paper_final2
exp_id: robust_deit_small_patch16_224_fgvc-aircraft-2013b_TRADES_v2
statedicts_path: /home/rishika/scratch/robust_training_data/state_dicts
trained_statedicts_path: /home/rishika/scratch/robust_training_data/trained_state_dicts/
datasets_path: /home/rishika/scratch/robust_training_data/compressed_datasets
hpo_path: /home/rishika/scratch/robust_training_data/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
