dataset: flowers-102
backbone: vit_base_patch16_clip_224.laion2b_ft_in1k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 50
lr1: 2.3187283452990446e-05
lr2: 1.977953176726232e-06
weight_decay1: 0.00048096354537337677
weight_decay2: 0.0002356470857433856
scheduler: true
nb_completed_trials: 229
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_paper_final2
exp_id: vit_base_patch16_clip_224.laion2b_ft_in1k_flowers-102_TRADES_v2
statedicts_path: /home/rishika/scratch/robust_training_data/state_dicts
trained_statedicts_path: /home/rishika/scratch/robust_training_data/trained_state_dicts/
datasets_path: /home/rishika/scratch/robust_training_data/compressed_datasets
hpo_path: /home/rishika/scratch/robust_training_data/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
