dataset: fgvc-aircraft-2013b
backbone: vit_small_patch16_224.augreg_in1k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 50
lr1: 0.0004647746719721332
lr2: 0.05619409646508126
weight_decay1: 9.380767542427003e-05
weight_decay2: 0.00014534564894374584
scheduler: false
nb_completed_trials: 212
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_paper_final2
exp_id: vit_small_patch16_224.augreg_in1k_fgvc-aircraft-2013b_CLASSIC_AT
statedicts_path: /home/rishika/scratch/robust_training_data/state_dicts
trained_statedicts_path: /home/rishika/scratch/robust_training_data/trained_state_dicts/
datasets_path: /home/rishika/scratch/robust_training_data/compressed_datasets
hpo_path: /home/rishika/scratch/robust_training_data/hpo_results/
work_path: $SLURM_TMPDIR/
configs_path: ./configs/
results_path: ./results/
