wandb_version: 1

loss:
  desc: null
  value: Madry
learning_rate:
  desc: null
  value: 0.01
scheduler:
  desc: null
  value: sched
rounds:
  desc: null
  value: 1
size:
  desc: null
  value: 5.0
epochs:
  desc: null
  value: 5
seed:
  desc: null
  value: 0
active_strategy:
  desc: null
  value: random
dataset:
  desc: null
  value: CIFAR10
model:
  desc: null
  value: resnet50
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.17.5
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723046996
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      3:
      - 2
      - 4
      - 13
      - 16
      - 23
      - 42
      4: 3.11.4
      5: 0.17.5
      6: 4.41.2
      8:
      - 5
      - 9
      13: linux-x86_64
