dataset: "kvasir-dataset"  # dataset (default: cifar10)
backbone: "convnext_tiny.fb_in1k"  # load backbone
ft_type: "full_fine_tuning"  # fine tuning type

loss_function: "CLASSIC_AT"  # TRADES_v2
seed: 0  # random seed
epochs: 5  # number of total iterations to run

lr1: null
lr2: null
weight_decay1: null
weight_decay2: null
scheduler: null

use_rs: False
epsilon: 0.015686275  # epsilon of trades (4/255)
step_size: 0.007843137  # step size of trades (2/255)
perturb_steps: 10  # number of steps of trades
distance: "Linf"  # distance of trades
beta: 1.0  # beta of trades

# arguments for diffusion augmented learning
project_name: null # the experiment type
exp_id: null

statedicts_path: "~/scratch/state_dicts_share/"  # TODO: update, where we load the pretrained model
datasets_path: "$SLURM_TMPDIR/data" # where we load uncompressed dataset
configs_path: "./configs" # where we save the results of HPO
results_path: "./results" # where we save the measured accuracies

trained_statedicts_path: "$SLURM_TMPDIR/trained_state_dicts/" #"~/scratch/trained_state_dicts/" # TODO: update, where we save fine tuned model
hpo_path: "$SLURM_TMPDIR/hpo_results/" #"~/scratch/hpo_results/" # where we save the results of HPO



