dataset: uc-merced-land-use-dataset
backbone: convnext_base.clip_laion2b_augreg
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 5
lr1: 0.014504210380141507
lr2: 7.413049158258723e-05
weight_decay1: 6.321730616286662e-06
weight_decay2: 0.0005269388986481306
scheduler: true
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_final1
