dataset: stanford_cars
backbone: CLIP-convnext_base_w-laion2B-s13B-b82K
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 5
lr1: 0.0001737404360263286
lr2: 0.0288854647855878
weight_decay1: 3.238451256068134e-05
weight_decay2: 0.00014246191473875792
scheduler: false
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_paper_final2
exp_id: CLIP-convnext_base_w-laion2B-s13B-b82K_stanford_cars_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
