dataset: stanford_cars
backbone: convnext_tiny.fb_in22k_ft_in1k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 5
lr1: 6.297501095519689e-06
lr2: 1.0304113317178832e-05
weight_decay1: 5.305508573098379e-05
weight_decay2: 4.138163284038599e-05
scheduler: true
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_paper_final2
exp_id: convnext_tiny.fb_in22k_ft_in1k_stanford_cars_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
