dataset: stanford_cars
backbone: convnext_tiny.fb_in1k
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 5
lr1: 0.0018690411295990668
lr2: 4.455003448750706e-06
weight_decay1: 1.5046583533251499e-05
weight_decay2: 2.7749746347104038e-05
scheduler: false
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_paper_final2
exp_id: convnext_tiny.fb_in1k_stanford_cars_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
