dataset: stanford_cars
backbone: eva02_base_patch14_224.mim_in22k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 5
lr1: 0.002449088376750874
lr2: 9.83670035496699e-06
weight_decay1: 5.091011023284046e-05
weight_decay2: 2.3625714912312524e-05
scheduler: true
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_paper_final2
exp_id: eva02_base_patch14_224.mim_in22k_stanford_cars_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
