dataset: stanford_cars
backbone: vit_small_patch16_224.augreg_in1k
ft_type: full_fine_tuning
loss_function: CLASSIC_AT
seed: 1
epochs: 5
lr1: 2.0468786766734157e-05
lr2: 0.00019270396303570155
weight_decay1: 3.8371860757414634e-05
weight_decay2: 0.000831438206653479
scheduler: true
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_paper_final2
exp_id: vit_small_patch16_224.augreg_in1k_stanford_cars_CLASSIC_AT
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
