dataset: oxford-iiit-pet
backbone: vit_base_patch16_clip_224.laion2b
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 5
lr1: 0.0007382944045784731
lr2: 0.001321860509659087
weight_decay1: 6.879176075045679e-06
weight_decay2: 4.22034712713536e-06
scheduler: true
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_paper_final2
exp_id: vit_base_patch16_clip_224.laion2b_oxford-iiit-pet_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
