dataset: stanford_cars
backbone: CLIP-convnext_base_w-laion2B-s13B-b82K
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 50
lr1: 0.0001793480721178975
lr2: 0.005878824056644075
weight_decay1: 0.0032029975700290426
weight_decay2: 0.00378814552109712
scheduler: true
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_50epochs_final4
exp_id: CLIP-convnext_base_w-laion2B-s13B-b82K_stanford_cars_TRADES_v2
statedicts_path: ~/scratch/state_dicts_share/
trained_statedicts_path: ~/scratch/trained_state_dicts/
datasets_path: $SLURM_TMPDIR/data
configs_path: ./configs
results_path: ./results
hpo_path: ~/scratch/hpo_results/
